{"Timestamp":"2020-03-03T00:51:18.0668542+07:00","Level":"Error","MessageTemplate":"{\"Identity\":\"202003020551180664551176765\",\"TransactionId\":\"\",\"Server\":\"192.168.20.1\",\"Caller\":null,\"Client\":\"\",\"Location\":{\"ClassName\":\"CustomerGroupService\",\"Namespace\":\"Pelo.v2.Web.Services.CustomerGroup\",\"Function\":\"GetAll\"},\"Message\":\"Exception of type 'Pelo.Common.Exceptions.PeloException' was thrown.\",\"Data\":{\"Parameters\":[],\"ReturnValue\":null},\"LogType\":\"Exception\",\"Elapsed\":49,\"ExecDate\":\"2020-03-03T00:51:18.0664813+07:00\",\"Site\":null}"}
